version: '2.1'
services:
  postgres:
    image: arm64v8/postgres:9-stretch
    ports:
      - "7004:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
